apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    kubernetes.io/app: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      kubernetes.io/app: mediawiki
  template:
    metadata:
      labels:
        kubernetes.io/app: mediawiki
    spec:
      containers:
        - name: mediawiki-app
          image: raghavtest.azurecr.io/raghav/mediawiki:1.0.1
          ports:
            - containerPort: 80

