apiVersion: v1
kind: ConfigMap
metadata:
  name: mediawiki_sql_config
data: 
  mysql_usermgmt.sql: |-
    CREATE DATABASE wikidatabase; 
    GRANT ALL PRIVILEGES ON wikidatabase.* TO 'wiki'@'localhost';
    FLUSH PRIVILEGES;