apiVersion: v1
kind: ConfigMap
metadata:
  name: mediawiki-sql-config
data: 
  mysql_usermgmt.sql: |-
    CREATE DATABASE wikidatabase; 
    GRANT ALL PRIVILEGES ON wikidatabase.* TO 'wiki'@'mariadb-svc.dev-mediawiki.svc.cluster.local';
    FLUSH PRIVILEGES;